const path = require("path");
const express = require("express");
const compression = require("compression");
const morgan = require("morgan");
const cors = require("cors");
const helmet = require("helmet");
const dotenv = require("dotenv");
const connectDB = require("./config/db");

// ✅ Import the React Router Server Adapter
// If using React Router v7, use '@react-router/express'
// If using Remix, use '@remix-run/express'
const { createRequestHandler } = require("@react-router/express");

dotenv.config();
connectDB();

const app = express();

// 1. GLOBAL MIDDLEWARE
app.use(helmet({
    contentSecurityPolicy: false, // Required to avoid 'eval' errors in browser
    crossOriginEmbedderPolicy: false,
}));
app.use(cors());
app.use(compression());
app.use(express.json());
app.use(morgan("tiny"));

// 2. YOUR API ROUTES (Must be ABOVE the React Router handler)
app.use("/api/auth", require("./routes/authRoutes"));
app.use("/api/company", require("./routes/companyRoutes"));
app.use("/api/masters", require("./routes/masterRoutes"));
app.use("/api/sites", require("./routes/siteRoutes"));
app.use("/api/inventory", require("./routes/inventoryRoutes"));
app.use("/api/sales", require("./routes/salesRoutes"));
app.use("/api/store", require("./routes/storeRoutes"));
app.use("/api/dashboard", require("./routes/dashboardRoutes"));
app.use("/api/admin", require("./routes/adminRoutes"));

// 3. SERVE STATIC ASSETS
// This serves all the CSS/JS files generated by the frontend build
app.use(
  "/assets",
  express.static(path.join(__dirname, "build/client/assets"), {
    immutable: true,
    maxAge: "1y",
  })
);
app.use(express.static(path.join(__dirname, "build/client"), { maxAge: "1h" }));

// 4. THE CATCH-ALL ROUTE (React Router SSR)
// This handles all navigation (Dashboard, Customers, etc.)
app.all("*", (req, res, next) => {
  try {
    return createRequestHandler({
      // @ts-ignore
      build: require("./build/server/index.js"),
    })(req, res, next);
  } catch (error) {
    next(error);
  }
});

const PORT = process.env.PORT || 5000;
app.listen(PORT, "0.0.0.0", () => {
  console.log(`🚀 ScaffRent Monolith Running on port ${PORT}`);
});